name: Build Test

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install node_modules
        run: npm install

      - name: Run Test
        run: npm test
        env:
          NODE_ENV: test

      - name: Deploy Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tuike-test"
          heroku_email: "pynhp9x@gmail.com"
          usedocker: true
        env:
          REACT_APP_ENV: test

